name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
      fail-fast: false  

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -e ".[pr_review]"
        
    - name: Create conftest.py to patch problematic methods
      run: |
        mkdir -p jupyter_ai_personas/pr_review_persona
        echo 'import pytest' > jupyter_ai_personas/pr_review_persona/conftest.py
        echo 'from unittest.mock import patch' >> jupyter_ai_personas/pr_review_persona/conftest.py
        echo '@pytest.fixture(autouse=True, scope="session")' >> jupyter_ai_personas/pr_review_persona/conftest.py
        echo 'def patch_persona_awareness():' >> jupyter_ai_personas/pr_review_persona/conftest.py
        echo '    with patch("jupyter_ai.personas.persona_awareness.PersonaAwareness._start_heartbeat", return_value=None):' >> jupyter_ai_personas/pr_review_persona/conftest.py
        echo '        yield' >> jupyter_ai_personas/pr_review_persona/conftest.py
        
    - name: Run tests
      run: |
        pytest $(find . -type d -name "test" -o -path "*/*/test_*.py" | tr '\n' ' ') -v --log-cli-level=INFO
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}